apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-svc
spec:
  selector:
    matchLabels:
      app: auction-svc
  template:
    metadata:
      labels:
        app: auction-svc
    spec:
      containers:
      - name: auction-svc
        image: denizgirginer8/auctionservice
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"
        #ports:
        #- containerPort: <Port>
        env:
        - name: RabbitMq__Host
          value: rabbit-clusterip
        - name: RabbitMq__Username
          valueFrom:
            secretKeyRef:
              name: auction-secret
              key: rabbitUn
        - name: RabbitMq__Password
          valueFrom:
            secretKeyRef:
              name: auction-secret
              key: rabbitPw
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: auction-secret
              key: connectionString
        - name: IdentityServiceUrl
          value: https://id.denizgirginer.cloud
        - name: Kestrel__Endpoints__Grpc__Protocols
          value: Http2
        - name: Kestrel__Endpoints__Grpc__Url
          value: http://+:7777
        - name: Kestrel__Endpoints__WebApi__Protocols
          value: Http1
        - name: Kestrel__Endpoints__WebApi__Url
          value: Http://+:8080

--- # connect from inside
apiVersion: v1
kind: Service
metadata:
  name: auction-clusterip
spec:
  type: ClusterIP
  selector:
    app: auction-svc
  ports:
  - port: 80
    targetPort: 8080
    name: web
  - port: 7777
    targetPort: 7777
    name: grpc
  