apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: denizgirginer8/gatewayservice
        imagePullPolicy: Always
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"
        #ports:
        #- containerPort: <Port>
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ClientApp
          valueFrom:
              secretKeyRef:
                name: gateway-secret
                key: clientApp
        - name: IdentityServiceUrl
          value: https://id.denizgirginer.cloud
        - name: Kestrel__Endpoints__WebApi__Protocols
          value: Http1
        - name: Kestrel__Endpoints__WebApi__Url
          value: Http://+:8080

--- # connect from inside
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 8080
    name: web