apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: rabbit
          - name: RABBITMQ_DEFAULT_PASS
            value: rabbit
        #resources:
        #  limits:
        #    memory: "128Mi"
        #    cpu: "500m"
        ports:
        - containerPort: 15672
          name: rbmq-mgmt-port
        - containerPort: 5672
          name: rbmq-msg-port
        volumeMounts:
        - mountPath: /var/data/rabbit
          name: rabbitdata
      volumes:
      - name: rabbitdata
        persistentVolumeClaim:
          claimName: rabbit-claim

--- # connect from inside
apiVersion: v1
kind: Service
metadata:
  name: rabbit-clusterip
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - port: 5672
    targetPort: 5672

--- # connect from outside
apiVersion: v1
kind: Service
metadata:
  name: rabbit-lb
spec:
  type: LoadBalancer
  selector:
    app: rabbitmq
  ports:
  - port: 15672 #outside port
    targetPort: 15672 #inside port


