apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: postgrespw

---

apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: rabbit
  password: rabbit

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: mongo
  password: mongopw

---

apiVersion: v1
kind: Secret
metadata:
  name: auction-secret
type: Opaque
stringData:
  connectionString: Server=postgres-clusterip;User Id=postgres;Password=postgrespw;Database=auctions

---

apiVersion: v1
kind: Secret
metadata:
  name: search-secret
type: Opaque
stringData:
  connectionString: mongodb://mongo:mongopw@mongo-clusterip
  rabbitUn: rabbit
  rabbitPw: rabbit

---

apiVersion: v1
kind: Secret
metadata:
  name: notify-secret
type: Opaque
stringData:
  rabbitUn: rabbit
  rabbitPw: rabbit

---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-secret
type: Opaque
stringData:
  authSecret: authsecret
  clientSecret: secret

---
apiVersion: v1
kind: Secret
metadata:
  name: bid-secret
type: Opaque
stringData:
  rabbitUn: rabbitUn 
  rabbitPw: rabbitSecretPw
  connectionString: 'mongodb://mongo:mongopw@mongo-clusterip'